// -*- c++ -*-

module sof { 
	module framework {
		module remote {
			module corba {
				module registry {
					module generated {

	interface RemoteService
	{
	};

	struct RemoteServiceProps
	{
		sequence<string> keys;
		sequence<string> values;
	};	

	struct RemoteServiceReference
	{
		string serviceName;
		RemoteServiceProps props;
		RemoteService service;
	};

	struct RemoteServiceEvent
	{
		short serviceType;
		RemoteServiceReference serviceRef;
	};	
	
	
	interface RemoteServiceListener
	{	
		boolean serviceChanged( in RemoteServiceEvent serviceEvent );
	};

	interface RemoteRegistryObserver 
	{		
		void registerService( in string bundleName, in string serviceName, in RemoteService service, in RemoteServiceProps props );
		void registerServiceListener( in string bundleName, in string serviceName, in RemoteServiceListener listener );
	};

	interface RemoteRegistry 
	{
		void addRegistryObserver( in RemoteRegistryObserver observer );		
		void registerService( in string bundleName, in string serviceName, in RemoteService service, in RemoteServiceProps props );
		void registerServiceListener( in string bundleName, in string serviceName, in RemoteServiceListener listener );
	};


};
};
};
};
};
};


